### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by nifker** [sugiany/blender_mmd_tools#33]
I get an  as I tried to import the TDA Convergence Luka Append Model: http://puu.sh/gaRG0/8cbab423bf.png

**Comment by sugiany** [comment]
Thank you very much for your report.

This problem is caused by the too long model name in the pmx file. In Blender, the length of an object name seems to be limited about 20 characters, so a long model name in a pmx file makes a corrupted object name.

You can import the model if you shorten the model name in the pmx file with PmxEditor.

I'm going to fix, but the release of a stable version is likely to be late.
