### ISSUE TITLE
cant convert materials for cycles in 2.78

### ISSUE THREAD

**Issue by moonrailgun** [sugiany/blender_mmd_tools#56]
neither 4.0 nor 5.0 can convert materials for cycles and report error like this

```
Traceback (most recent call last):
  File "G:\Blender\2.78\scripts\addons\mmd_tools\operators\material.py", line 18, in execute
    cycles_converter.convertToCyclesShader(obj)
  File "G:\Blender\2.78\scripts\addons\mmd_tools\cycles_converter.py", line 143, in convertToCyclesShader
    i.material.node_tree.links.new(i.material.node_tree.nodes['Material Output'].inputs['Surface'], outplug)
KeyError: 'bpy_prop_collection[key]: key "Material Output" not found'

location: <unknown location>:-1
```
hope to fix it

**Comment by powroupi** [comment]
The issue has been fixed in my branch [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test). You might try it, or just download the raw file *cycles_converter.py* from [this page](https://github.com/powroupi/blender_mmd_tools/blob/dev_test/mmd_tools/cycles_converter.py) (or download directly -> [cycles_converter.py](https://github.com/powroupi/blender_mmd_tools/raw/dev_test/mmd_tools/cycles_converter.py)) and replace your old one. Thank you. :smile:

**Comment by moonrailgun** [comment]
thank you for fix it and hope to merge to master branch or tell others . i think lots of people hope this too
:)

**Comment by moonrailgun** [comment]
this issue will be close
